# Analysis on Generative AI

In [2]:
## Import Libraries
import numpy as np
import pandas as pd

In [4]:
## Read datasets
model_detail = pd.read_excel('Generative AI.xlsx', sheet_name = 'model_detail')
performance_detail = pd.read_excel('Generative AI.xlsx', sheet_name = 'performance_detail')

In [6]:
model_detail.head(20)

         Model Name Model Creator  Launch Year            Special Feature
0             GPT-3        OpenAI         2020            Text Completion
1             GPT-4        OpenAI         2023         Advanced Reasoning
2            DALL·E        OpenAI         2021           Image Generation
3           ChatGPT        OpenAI         2023          Conversational AI
4  Stable Diffusion  Stability AI         2022             Open-Source AI
5        MidJourney    MidJourney         2022  Creative Image Generation

In [8]:
performance_detail.head(20)

,Model Name,Accuracy (%),Training Time (hrs),Generated Content,Data Type,Date Created,Model Version
0,GPT-3,92.5,72,Text,Text,2020-01-01,1.0
1,GPT-4,95.0,90,Text,Text,2024-01-10,1.1
2,DALL·E,87.0,60,Image,Image,2024-02-01,1.0
3,GPT-3.5,91.2,80,Text,Text,2024-01-05,1.0
4,DALL·E 2,88.5,70,Image,Image,2024-02-10,2.0
5,Stable Diffusion,85.0,65,Image,Image,2024-01-15,1.0
6,ChatGPT,93.5,75,Text,Text,2024-01-20,1.0
7,GPT-2,89.0,50,Text,Text,2024-01-12,1.0
8,MidJourney,92.0,80,Image,Image,2024-02-05,2.0

In [10]:
# Rename Columns
performance_detail.rename(columns={'Accuracy (%)':'Accuracy','Model Version':'Version'}, inplace = True)

In [12]:
performance_detail.head(10)

,Model Name,Accuracy,Training Time (hrs),Generated Content,Data Type,Date Created,Version
0,GPT-3,92.5,72,Text,Text,2020-01-01,1.0
1,GPT-4,95.0,90,Text,Text,2024-01-10,1.1
2,DALL·E,87.0,60,Image,Image,2024-02-01,1.0
3,GPT-3.5,91.2,80,Text,Text,2024-01-05,1.0
4,DALL·E 2,88.5,70,Image,Image,2024-02-10,2.0
5,Stable Diffusion,85.0,65,Image,Image,2024-01-15,1.0
6,ChatGPT,93.5,75,Text,Text,2024-01-20,1.0
7,GPT-2,89.0,50,Text,Text,2024-01-12,1.0
8,MidJourney,92.0,80,Image,Image,2024-02-05,2.0

In [14]:
# Search for value in column
performance_detail[performance_detail['Model Name'] == 'ChatGPT']

,Model Name,Accuracy,Training Time (hrs),Generated Content,Data Type,Date Created,Version
6,ChatGPT,93.5,75,Text,Text,2024-01-20,1.0

## How to find missing values?

In [17]:
# Missing values
performance_detail.isna().sum()

Model Name             0
Accuracy               0
Training Time (hrs)    0
Generated Content      0
Data Type              0
Date Created           0
Version                0
dtype: int64

In [19]:
performance_detail.dtypes

Model Name                     object
Accuracy                      float64
Training Time (hrs)             int64
Generated Content              object
Data Type                      object
Date Created           datetime64[ns]
Version                       float64
dtype: object

## How to Filter Based on Multiple Conditions?

In [22]:
## Find models which are Text and have Training Time (hrs) less than 90
performance_detail[(performance_detail['Data Type'] == 'Text') & (performance_detail['Training Time (hrs)'] < 90)]

,Model Name,Accuracy,Training Time (hrs),Generated Content,Data Type,Date Created,Version
0,GPT-3,92.5,72,Text,Text,2020-01-01,1.0
3,GPT-3.5,91.2,80,Text,Text,2024-01-05,1.0
6,ChatGPT,93.5,75,Text,Text,2024-01-20,1.0
7,GPT-2,89.0,50,Text,Text,2024-01-12,1.0

## How to Group By

In [25]:
## calculate average training time and accuracy by data type
performance_detail.groupby('Data Type').agg({'Accuracy':'mean', 'Training Time (hrs)' : 'mean' })

           Accuracy  Training Time (hrs)
Data Type
Image        88.125                68.75
Text         92.240                73.40

## How to Join DataFrames?

In [28]:
pd.merge(model_detail, performance_detail, on = 'Model Name', how = 'inner')

,Model Name,Model Creator,Launch Year,Special Feature,Accuracy,Training Time (hrs),Generated Content,Data Type,Date Created,Version
0,GPT-3,OpenAI,2020,Text Completion,92.5,72,Text,Text,2020-01-01,1.0
1,GPT-4,OpenAI,2023,Advanced Reasoning,95.0,90,Text,Text,2024-01-10,1.1
2,DALL·E,OpenAI,2021,Image Generation,87.0,60,Image,Image,2024-02-01,1.0
3,ChatGPT,OpenAI,2023,Conversational AI,93.5,75,Text,Text,2024-01-20,1.0
4,Stable Diffusion,Stability AI,2022,Open-Source AI,85.0,65,Image,Image,2024-01-15,1.0
5,MidJourney,MidJourney,2022,Creative Image Generation,92.0,80,Image,Image,2024-02-05,2.0

## Create a function to find mismatch

## 
This function Merges two dataframes, extracts the year from the "Date Created" column,
    and identifies mismatches between "Launch Year" and the extracted year.

In [32]:
def process_and_find_mismatches(df1, df2):
    merged_df = pd.merge(df1,df2, on='Model Name', how = 'inner')

    merged_df['Date Created'] = pd.to_datetime(merged_df['Date Created'])

    merged_df['Extracted Year'] = merged_df['Date Created'].dt.year

    merged_df['Year Mismatch'] = merged_df['Launch Year'] != merged_df['Extracted Year']

    return merged_df

In [34]:
process_and_find_mismatches(model_detail, performance_detail)

,Model Name,Model Creator,Launch Year,Special Feature,Accuracy,Training Time (hrs),Generated Content,Data Type,Date Created,Version,Extracted Year,Year Mismatch
0,GPT-3,OpenAI,2020,Text Completion,92.5,72,Text,Text,2020-01-01,1.0,2020,False
1,GPT-4,OpenAI,2023,Advanced Reasoning,95.0,90,Text,Text,2024-01-10,1.1,2024,True
2,DALL·E,OpenAI,2021,Image Generation,87.0,60,Image,Image,2024-02-01,1.0,2024,True
3,ChatGPT,OpenAI,2023,Conversational AI,93.5,75,Text,Text,2024-01-20,1.0,2024,True
4,Stable Diffusion,Stability AI,2022,Open-Source AI,85.0,65,Image,Image,2024-01-15,1.0,2024,True
5,MidJourney,MidJourney,2022,Creative Image Generation,92.0,80,Image,Image,2024-02-05,2.0,2024,True